### ISSUE TITLE
Import login re-direct

### ISSUE THREAD

**Issue by borpin** [emoncms/backup#32] opened 2019-04-28 16:57 UTC
Status, flashed Oct18 SD, let update run.

On importing data I get this error
![image](https://user-images.githubusercontent.com/1322749/56867612-e9f03300-69de-11e9-818c-d756f8044853.png)

And it seems to have logged me out as I get an error if I try to access the administration screen

**Comment by glynhudson** [comment] 2019-04-30 15:57
The import process should log you out once the import is successful. Can you login with your imported account now? It would be good to redirect to the login page

**Comment by borpin** [comment] 2019-04-30 16:10
That makes sense and yes, the import apparently works, the error is rather misleading then, as it implies the import has failed.

**Comment by glynhudson** [comment] 2019-04-30 16:47
@TrystanLea I wonder how we could implement a re-direct to the login page since the last line of the import script restarts apache2: https://github.com/emoncms/backup/blob/master/emoncms-import.sh#L189

Obviously at this point we lose control of the browser. It's important for the import log window to display the import process before then.

**Comment by glynhudson** [comment] 2019-04-30 16:48
Duplicate of https://github.com/emoncms/backup/issues/17

**Closed as completed** 2023-02-10 21:27 UTC
Labels: enhancement
